## Index Rules
meta:
  index: noindex ## noindex, index

seo:
  title: Billy Carlson
  description: 
  keywords: 
  divider: '&mdash;'
  image:

social:
  facebook:
  google:
  twitter:
  youtube:

favicon:
  ico: /dist/ico/favicon.ico
  57x57: /dist/ico/apple-touch-icon.png
  64x64: /dist/ico/favicon.png
  72x72: /dist/ico/apple-touch-icon-72x72.png
  114x114: /dist/ico/apple-touch-icon-114x114.png
  144x144: /dist/ico/apple-touch-icon-144x144.png
  60x60: /dist/ico/apple-touch-icon-60x60-precomposed.png
  76x76: /dist/ico/apple-touch-icon-76x76-precomposed.png
  120x120: /dist/ico/apple-touch-icon-120x120-precomposed.png
  152x152: /dist/ico/apple-touch-icon-152x152-precomposed.png
  228x228: /dist/ico/coast-icon-228x228.png
  square70x70logo: /dist/ico/windows-tile-70x70.png
  square150x150logo: /dist/ico/windows-tile-150x150.png
  square310x310logo: /dist/ico/windows-tile-310x310.png
  square144x144logo: /dist/ico/windows-tile-144x144.png
  titlecolor: '#000000'